version: '3'
services:
  http-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
